### PR TITLE
Optionally skip logging QRCode to console and add optional authTimeout config option

### PR DESCRIPTION
**Pull request by sandro-salles**
**Skipping QRCode logging**

If you want to avoid logging the generated QRCode to console, just pass a qrLogSkip=true. 

Eg.:

```
create({
        sessionId: `mySessionsId`,        
        qrLogSkip: true
      })
      .then(async (client) => {
        ...
      })
```

**Authentication timeout**

If the user has previously logged in (have an already existing session), and when trying to authenticate again but the mobile device is turned off or without and active internet connection, the isAthenticated promise never resolves.

With this update, by passing authTimeout=NUMBER_OF_SECONDS, after that amout of time, isAuthenticated gives up and the there's a check to see if whatsapp page is displaying the **Trying to reach phone** count down. If true, an Error is thrown - _throw new Error('OUTOFREACH')_

You can then free the browser and as users to turn on their phones (or internet connections). 

Eg.:

```
create({
        sessionId: `mySessionsId`, 
        authTimeout: 45 // will give up authentication after 45 seconds
      })
      .then(async (client) => {
        ...
      })
      .catch((error) => {
        if (error.message === "OUTOFREACH") {
         // do something....
        });
```

@smashah hope you find it useful (and this time i turned off prettier automatic linting here hehe)

Regards

### CODE REVIEW

**Comment by smashah** [comment]
@sandro-salles unable to merge PR due to linting issue again. Added qrLogSkip. Will implement something like authTimeout later (will need to rename `killTimer` to `qrTimeout`). Ideally the values for both would be the same (i.e if you wait 40 seconds for a qr scan, why wait any longer or shorter for authentication to complete?)

Thanks, for future reference just make an `[feature]` issue and add the code to be added. would be relatively quicker.

Thanks

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//comment on the issue
var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.9.18](https://github.com/open-wa/wa-automate-nodejs/compare/1.9.17...1.9.18) (2020-05-10)

- Release 1.9.18 [`f7f1adb`](https://github.com/open-wa/wa-automate-nodejs/commit/f7f1adbf9e980ce8445c1c204889a982604677ce)
- chore: remove buttons.js [`6aa99e1`](https://github.com/open-wa/wa-automate-nodejs/commit/6aa99e1d5c9cdc0225a53ec22d67600b9b0e9308)
- [FEATURE] Implemented qrLogSkip from #419 [`14587cd`](https://github.com/open-wa/wa-automate-nodejs/commit/14587cd79ce4d23b730f098107b47ea15deef62b)
- updated dep: open-wa - new feature: bleachMessage [`12d5122`](https://github.com/open-wa/wa-automate-nodejs/commit/12d5122e8a62a5b84c71f30def18b6eb5fe64926)
- chore: clean unused files [`32584a5`](https://github.com/open-wa/wa-automate-nodejs/commit/32584a5e1a4b7a1df08b6c73d469e2269a4bf170)
- updated release-image [`95e861d`](https://github.com/open-wa/wa-automate-nodejs/commit/95e861da6fcc0f6c7dc5c3814ce7240ea9a7485d)

**Comment by sandro-salles** [comment]
Ok @smashah , next will be feature issue!

Regarding **qrTimeout** vs **authTimeout**, the main reason for having them separated is to be able to catch different errors for each situation, as the instructions/feedback for final users are different for each scenario...

**Pull request closed without merging**
