### PR TITLE
removed all `done` params from wapi.js

### PR DESCRIPTION
**Pull request by smashah**
Simplifying wapi.js by removing all done callback parameters.

Todo:

- [x] Add python wrapper function
- [x] Lazy-inject jsSha
- [x] Fix simulated Typing

cc @mrodal

### CODE REVIEW

**Comment by mrodal** [comment]
Nice! Its much cleaner now
Always returning promises is still pending right?

**Comment by smashah** [comment]
@mrodal I did most of them, however, some didn't need to be converted. Also, it is perfectly fine to await a non-async function.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

//create changelog image
exec(`npm run release-image`);
exec(`git commit -a -m 'updated release-image'`);
exec(`git push --force`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.62](https://github.com/open-wa/wa-automate-nodejs/compare/1.8.61...1.8.62) (2020-04-16)

- removed all `done` params from wapi.js [`#326`](https://github.com/open-wa/wa-automate-nodejs/pull/326)
- Release 1.8.62 [`8017525`](https://github.com/open-wa/wa-automate-nodejs/commit/8017525c9f88cf838b8779cbb193a7da8bc64292)
- updated release image [`edc97e3`](https://github.com/open-wa/wa-automate-nodejs/commit/edc97e3e781a8c3bcff85c09c2ce77e8f34131ba)

**Pull request merged**
